/* AUTO-GENERATED FILE — DO NOT EDIT*/
/* Generated by scripts/generate-provincias-municipios.ts*/

import { MunicipiosPorProvincia } from '@/constants/municipios-por-provincia.constant'
import { Provincias } from '@/constants/provincias.constant'

export type Provincia = (typeof Provincias)[keyof typeof Provincias]

export type Municipio = (typeof MunicipiosPorProvincia)[keyof typeof MunicipiosPorProvincia][number]
