/* AUTO-GENERATED FILE — DO NOT EDIT*/
/* Generated by scripts/generate-provincias-municipios.ts*/

import { MunicipiosPorProvincia } from '@/constants/municipios-por-provincia.constant'
import { ProvinciaPorMunicipio } from '@/constants/provincia-por-municipio.constant'
import { Municipio, Provincia } from '@/types/municipio-provincia.type'

export function getMunicipiosByProvincia(provincia: Provincia): readonly Municipio[] {
	return MunicipiosPorProvincia[provincia]
}

export function getProvinciaByMunicipio(municipio: Municipio): Provincia {
	return ProvinciaPorMunicipio[municipio]
}
